Sprint 3
ClevertecFrontendLab/Ratiborz pull request #3
Opened 2024-03-04 20:53 UTC by Ratiborz

2024-03-04 21:27 UTC, byshlata requested changes

2024-03-04 21:27 UTC, byshlata commented on src/api/feedbackRequests.ts
> +    return httpClient.get('feedback');
return можно и не писать в таком случае

2024-03-04 21:27 UTC, byshlata commented on src/components/auth/auth/auth.tsx
>              history.push('/main');
main лучше бы занести куда-то в перменные

2024-03-04 21:27 UTC, byshlata commented on src/components/auth/auth/auth.tsx
> +        window.location.href = 'https://marathon-api.clevertec.ru/auth/google';
baseUrl же у тебя есть переменная

2024-03-04 21:27 UTC, byshlata commented on src/components/auth/auth/auth.tsx
>  import s from './auth.module.scss';
s хорошая буква, но нужно написать, что-то понятное. styles например

2024-03-04 21:27 UTC, byshlata commented on src/components/feedback/first-feedback/firstFeedback.module.scss
> +    font-size: 24px;
переменный неплохо бы занести куда-то отдельно, а не дублировать

2024-03-04 21:27 UTC, byshlata commented on src/components/feedback/first-feedback/firstFeedback.tsx
> +                onClick={() => dispatch(actions.setStateModalError(true))}
это нужно вынести в функцию вверху, так читаеться не очень

2024-03-04 21:27 UTC, byshlata commented on src/components/feedback/modal-error/modalError.tsx
> +                        handleChangeModal();
вынести

2024-03-04 21:27 UTC, byshlata commented on src/pages/feedback-page/feedbackPage.tsx
> +            if ((error as FetchBaseQueryError).status === 403) {
статусы ошибок тоже нужно в переменные

2024-03-04 21:42 UTC, vvikota requested changes

2024-03-04 21:42 UTC, vvikota commented on src/components/main-page/footer/footer.tsx
> +    };
фигурные скобки не нужны

2024-03-04 21:42 UTC, vvikota commented on src/components/main-page/sider/sider.tsx
>          history.push('/auth');
пути в константы вынести нужно

2024-03-05 10:28 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**empty-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Ratiborz/1709634522/empty-review-list.png)
***
**expand-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Ratiborz/1709634522/expand-review-list.png)
***
**get-feedback-error.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Ratiborz/1709634522/get-feedback-error.png)
***
**more-than-4-reviews.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Ratiborz/1709634522/more-than-4-reviews.png)
***
**one-review.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Ratiborz/1709634522/one-review.png)
***
**review-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Ratiborz/1709634522/review-modal.png)
***
**reviews-not-saved-modal.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Ratiborz/1709634522/reviews-not-saved-modal.png)
***
**updated-review-list.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Ratiborz/1709634522/updated-review-list.png)

2024-03-05 10:30 UTC, byshlata approved these changes

2024-03-05 11:40 UTC, vvikota approved these changes

2024-03-05 13:10 UTC, merged